Hello All, Welcome to Harsha Trainings !!!
Now devops job market is good.. all the best
All the best....................
Tomorrow We will be having 3rd project which is Kubernetes Project....................
Also Python Scripting.............
